.Dd August 13, 2022
.Dt XPAVM 1
.Sh NAME
.Nm xpavm
.Nd simple pulseaudio volume manager for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh CONTROLS
.Bl -bullet -compact -width indent
.It
select a different sink with j/k keys
.It
decrease/increase volume of sink with h/l keys
.It
toggle mute of sink with m key
.It
exit the program with q/escape keys
.El
.Sh SEE ALSO
.Xr X 7
.Xr pulseaudio 1
.Xr pactl 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xpavm/issues
