.TH XPAVM 1 "March 23, 2022"
.SH NAME
xpavm \- simple X11 program to control pulseaudio sink inputs volume.
.SH SYNOPSIS
\fBautolayout\fP [ -hk ]
.SH OPTIONS
.TP
\fB\-k\fR, \fB\-\-keybidings\fR
display the keybindings
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit
.SH BUGS
https://github.com/alpheratz0/xpavm/issues
