.Dd February 05, 2026
.Dt OPILION 1
.Sh NAME
.Nm opilion
.Nd simple pulseaudio volume manager for X
.Sh SYNOPSIS
.Nm
.Op Fl hvIsma
.Op Cm +sma
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl I
hide application icons
.It Fl s , Cm +s
hide/show speakers
.It Fl m , Cm +m
hide/show microphones
.It Fl a , Cm +a
hide/show applications
.El
.Sh KEYBOARD BINDINGS
.Bl -tag -width indent
.It F5
Refresh sinks.
.It D
Make sink/source default.
.It dd
Kill sink.
.It m
Toggle sink mute.
.It i
Toggle sink isolate.
.It h
Decrease sink volume.
.It l
Increase sink volume.
.It j
Select sink below.
.It k
Select sink above.
.It z
Toggle visibility of speakers.
.It x
Toggle visibility of microphones.
.It c
Toggle visibility of applications.
.It Escape/q
Exit the application.
.El
.Sh SEE ALSO
.Xr X 7
.Xr pulseaudio 1
.Xr pactl 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/opilion/issues
