.Dd September 10, 2023
.Dt XPAVM 1
.Sh NAME
.Nm xpavm
.Nd simple pulseaudio volume manager for X
.Sh SYNOPSIS
.Nm
.Op Fl hvw
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl w
start in windowed mode instead of fullscreen
.El
.Sh KEYBOARD BINDINGS
.Bl -tag -width indent
.It F5
Refresh sinks.
.It m
Toggle sink mute.
.It h
Decrease sink volume.
.It l
Increase sink volume.
.It j
Select sink below.
.It k
Select sink above.
.It Escape/q
Exit the application.
.El
.Sh SEE ALSO
.Xr X 7
.Xr pulseaudio 1
.Xr pactl 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xpavm/issues
